name: CI/CD Pipeline for PWA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Facultatif : lancer le projet localement (souvent inutile en CI)
      # - name: Start dev server (facultatif, utile uniquement avec tests ou preview)
      #   run: npm start
